version: "2.6"
services:
  www:
    build: .
    ports:
      - "8000:80"
    volumes:
      - ./www:/var/www/html/
  db:
    image: mysql:8
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: ie4717
      MYSQL_USER: user
      MYSQL_PASSWORD: test
      MYSQL_ROOT_PASSWORD: test
    volumes:
      - ie4717-database:/var/lib/mysql
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - 8000:80
    environment:
      MYSQL_USER: user
      MYSQL_PASSWORD: test
      MYSQL_ROOT_PASSWORD: test
volumes:
  ie4717-database:
