version: "3"

includes:
  ci: ./scripts/ci.yml
  fmt: ./scripts/fmt.yml
  ide: ./scripts/ide.yml
  lint: ./scripts/lint.yml

tasks:
  cfg:scripts:
    desc: Make all scripts executable
    cmds:
      - chmod -R +x ./scripts

  setup:
    desc: Setup the working environment
    cmds:
      - docker volume create ie4717-mysql-volume

  start:
    desc: Startup Docker server
    cmds:
      - docker compose up -d
      - browser-sync start -p "localhost:8031" --files "src/**/*.*"

  stop:
    desc: Stop Server
    cmds:
      - docker compose down

  reset:db:
    desc: Restarts the database
    cmds:
      - docker volume rm ie4717-mysql-volume
      - docker volume create ie4717-mysql-volume

  lint:
    desc: Run all Linters
    cmds:
      - task: lint:run

  fmt:
    desc: Run all Formatters
    cmds:
      - task: fmt:run
