INSERT INTO Movies (name, trailer, description, release_date, rating, duration)
VALUES ('Don\'t Worry Darling', 'https://www.youtube.com/embed/FgmnKsED-jU',
        'A 1950s housewife living with her husband in a utopian experimental community begins to worry that his glamorous company could be hiding disturbing secrets.',
        '2022-09-23', 6, 123),
       ('Top Gun: Maverick', 'https://www.youtube.com/embed/qSqVVswa420',
        'After thirty years, Maverick is still pushing the envelope as a top naval aviator, but must confront ghosts of his past when he leads TOP GUN\'s elite graduates on a mission that demands the ultimate sacrifice from those chosen to fly it.',
        '2022-05-27', 8, 130),
       ('Pearl', 'https://www.youtube.com/embed/L5PW5r3pEOg',
        'Trapped on her family\'s isolated farm, Pearl must tend to her ailing father under the bitter and overbearing watch of her devout mother. Lusting for a glamorous life like she\'s seen in the movies, Pearl finds her ambitions, temptations, and repressions all colliding in this origin story of X\'s iconic villain.',
        '2022-09-16', 7, 103),
       ('Everything Everywhere All at Once', 'https://www.youtube.com/embed/wxN1T1uxQ2g',
        'An aging Chinese immigrant is swept up in an insane adventure, in which she alone can save the world by exploring other universes connecting with the lives she could have led.',
        '2022-05-13', 8, 139),
       ('The Northman', 'https://www.youtube.com/embed/oMSdFM12hOw',
        'The Viking Age. With a mind aflame with hate and revenge, Prince Amleth, the wronged son of King Aurvandill War-Raven, heads to cold, windswept Iceland to retrieve what was stolen from him: a father, a mother, and a kingdom. And like a war dog picking up the enemy\'s scent, brutal Amleth embarks on a murderous quest to find the hateful adversary, whose life is forever woven together with his by the threads of fate. Now, in the name of Valhalla, no one can stop the Northman, not even God.',
        '2022-04-13', 7, 137),
       ('Nope', 'https://www.youtube.com/embed/In8fuzj3gck',
        'After random objects falling from the sky result in the death of their father, ranch-owning siblings OJ and Emerald Haywood attempt to capture video evidence of an unidentified flying object with the help of tech salesman Angel Torres and documentarian Antlers Holst.',
        '2022-08-12', 7, 130),
       ('Elvis', 'https://www.youtube.com/embed/wBDLRvjHVOY',
        'The life of American music icon Elvis Presley, from his childhood to becoming a rock and movie star in the 1950s while maintaining a complex relationship with his manager, Colonel Tom Parker.',
        '2022-06-24', 7, 159),
       ('The Batman', 'https://www.youtube.com/embed/mqqft2x_Aa4',
        'Batman ventures into Gotham City\'s underworld when a sadistic killer leaves behind a trail of cryptic clues. As the evidence begins to lead closer to home and the scale of the perpetrator\'s plans become clear, he must forge new relationships, unmask the culprit and bring justice to the abuse of power and corruption that has long plagued the metropolis.',
        '2022-03-04', 8, 176),
       ('The Unbearable Weight of Massive Talent', 'https://www.youtube.com/embed/x2YHPZMj8r4',
        'The fictionalized version of Nick Cage must accept a $1 million offer to attend the birthday of a dangerous super fan Javi Gutierrez. Things take a wildly unexpected turn when Nick Cage is recruited by a CIA operative Vivian and forced to live up to his own legend, channeling his most iconic and beloved on-screen characters in order to save himself and his loved ones.',
        '2022-04-22', 7, 107),
       ('Crimes of the Future', 'https://www.youtube.com/embed/xyCI741MqPY',
        'Humans adapt to a synthetic environment, with new transformations and mutations. With his partner Caprice, Saul Tenser, celebrity performance artist, publicly showcases the metamorphosis of his organs in avant-garde performances.',
        '2022-09-09', 6, 107),
       ('Moonage Daydream', 'https://www.youtube.com/embed/c70ko07julc',
        'A cinematic odyssey exploring David Bowie\'s creative and musical journey. From visionary filmmaker Brett Morgen, and sanctioned by the Bowie estate.',
        '2022-09-23', 8, 135),
       ('Boiling Point', 'https://www.youtube.com/embed/UBUfCL_tvro',
        'Enter the relentless pressure of a restaurant kitchen as a head chef wrangles his team on the busiest day of the year.',
        '2022-01-07', 8, 92),
       ('The Sadness', 'https://www.youtube.com/embed/VUR1DWh7eLs',
        'After a year of combating a pandemic with relatively benign symptoms, a frustrated nation finally lets its guard down. This is when the virus spontaneously mutates, giving rise to a mind-altering plague. The streets erupt into violence and depravity, as those infected are driven to enact the most cruel and ghastly things they can think of. Murder, torture, rape and mutilation are only the beginning. A young couple is pushed to the limits of sanity as they try to reunite amid the chaos. The age of civility and order is no more. There is only \"The Sadness\".',
        '2022-01-22', 7, 99),
       ('Smile', 'https://www.youtube.com/embed/BcDK7lkzzsU',
        'After witnessing a bizarre, traumatic incident involving a patient, Dr. Rose Cotter starts experiencing frightening occurrences that she can\'t explain. Rose must confront her troubling past in order to survive and escape her horrifying new reality.',
        '2022-09-28', 7, 105),
       ('The Shining', 'https://www.youtube.com/embed/FZQvIJxG9Xs',
        'A novelist - Jack Torrance takes a job interview as winter caretaker of the isolated, old, huge and beautiful Overlook Hotel. Jack brings his wife - Wendy and his son Danny. It happens that Danny, has a mysterious power known as \"The Shining\". Danny meets Hallorann - the hotel cook in their first day arriving at the Overlook, who warns him about the hotel and the sinister Room 237. As the days go by, Danny has visions, meanwhile Jack starts driving into insanity, turning more and more aggressive, at the point that Danny and Wendy gets convinced that Jack might try to do something bad.',
        '1980-10-05', 8, 146),
       ('Psycho', 'https://www.youtube.com/embed/Wz719b9QUqY',
        'Phoenix office worker Marion Crane is fed up with the way life has treated her. She has to meet her lover Sam in lunch breaks, and they cannot get married because Sam has to give most of his money away in alimony. One Friday, Marion is trusted to bank forty thousand dollars by her employer. Seeing the opportunity to take the money and start a new life, Marion leaves town and heads towards Sam\'s California store. Tired after the long drive and caught in a storm, she gets off the main highway and pulls into the Bates Motel. The motel is managed by a quiet young man called Norman who seems to be dominated by his mother.',
        '1960-09-15', 9, 109),
       ('American Psycho', 'https://www.youtube.com/embed/Wz719b9QUqY',
        'A wealthy New York City investment banking executive, Patrick Bateman, hides his alternate psychopathic ego from his co-workers and friends as he delves deeper into his violent, hedonistic fantasies.',
        '2000-04-21', 8, 102),
       ('Get Out', 'https://www.youtube.com/embed/DzfpyUB60YY',
        'Chris and his girlfriend Rose go upstate to visit her parents for the weekend. At first, Chris reads the family\'s overly accommodating behavior as nervous attempts to deal with their daughter\'s interracial relationship, but as the weekend progresses, a series of increasingly disturbing discoveries lead him to a truth that he never could have imagined.',
        '2017-03-17', 8, 104),
       ('IT (1990)', 'https://www.youtube.com/embed/m5JO8wtNnzQ',
        'In 1960, a group of social outcasts who are bullied by a gang of greasers led by Henry Bowers are also tormented by an evil demon who can shape-shift into a clown and feed on children\'s fears and kill them. After defeating the demonic clown as kids, it resurfaces thirty years later and they must finish it off as adults once again.',
        '1990-11-18', 7, 192),
       ('The Conjuring', 'https://www.youtube.com/embed/k10ETZ41q5o',
        'In 1971, Carolyn and Roger Perron move their family into a dilapidated Rhode Island farm house and soon strange things start happening around it with escalating nightmarish terror. In desperation, Carolyn contacts the noted paranormal investigators, Ed and Lorraine Warren, to examine the house. What the Warrens discover is a whole area steeped in a satanic haunting that is now targeting the Perron family wherever they go. To stop this evil, the Warrens will have to call upon all their skills and spiritual strength to defeat this spectral menace at its source that threatens to destroy everyone involved.',
        '2013-08-02', 8, 112),
       ('The Thing', 'https://www.youtube.com/embed/5ftmr17M-a4',
        'During an exploration in Antarctica, a group of researchers come across a Norwegian facility near their research station. They soon come to realize Something horrible happened there. After discovering that the Norwegians had stumbled across something horrific; they leave, but something comes back with them.',
        '1982-08-26', 8, 109),
       ('The Exorcist', 'https://www.youtube.com/embed/YDGw1MTEe9k',
        'A visiting actress in Washington, D.C., notices dramatic and dangerous changes in the behavior and physical make-up of her 12-year-old daughter. Meanwhile, a young priest at nearby Georgetown University begins to doubt his faith while dealing with his mother\'s terminal sickness. And, book-ending the story, a frail, elderly priest recognizes the necessity for a show-down with an old demonic enemy.',
        '1974-09-22', 8, 122),
       ('Scream', 'https://www.youtube.com/embed/i3J6ACKQ7K0',
        'A year after her mother\'s death, Sidney Prescott and her friends started experiencing some strange phone calls. They later learned the calls were coming from a crazed serial killer, in a white faced mask and a large black robe, looking for revenge. His phone calls usually consist of many questions, the main one being: What\'s your favorite scary movie? Along with much scary movie trivia, ending with bloody pieces of innocent lives scattered around the small town of Woodsboro.',
        '1996-12-18', 7, 111),
       ('Midsommar', 'https://www.youtube.com/embed/1Vnghdsjmd0',
        'Dani and Christian are a young American couple with a relationship on the brink of falling apart. But after a family tragedy keeps them together, Christian invites a grieving Dani to join him and his friends on a trip to a once-in-a-lifetime midsummer festival in a remote Swedish village. What begins as a carefree summer holiday in the North European land of eternal sunlight takes a sinister turn when the insular villagers invite their guests to partake in festivities that render the pastoral paradise increasingly unnerving and viscerally disturbing.',
        '2019-07-03', 7, 148),
       ('Hereditary', 'https://www.youtube.com/embed/V6wWKNij_1M',
        'When her mentally ill mother passes away, Annie, her husband, son, and daughter all mourn her loss. The family turn to different means to handle their grief, including Annie and her daughter both flirting with the supernatural. They each begin to have disturbing, otherworldly experiences linked to the sinister secrets and emotional trauma that have been passed through the generations of their family.',
        '2018-06-15', 7, 127);
